#!/opt/anaconda3/bin/python
# -*- coding: utf-8 -*-
###############################################################################
# Write SI LaTeX table of XGBoost Optuna search ranges + selected values
# from Data/Output/XGBoost_best_params.txt (produced by Code/2.3.XGBoost.py).
# Output: tex/xgb_hparams.tex
###############################################################################

from __future__ import annotations

from pathlib import Path

import pandas as pd

PROJECT = Path(__file__).resolve().parent.parent
PARAMS_PATH = Path(
    __import__("os").environ.get(
        "XGB_BEST_PARAMS",
        str(PROJECT / "Data" / "Output" / "XGBoost_best_params.txt"),
    )
)
OUT_TEX = PROJECT / "tex" / "xgb_hparams.tex"

COMBO_ORDER = ["yHxP", "yHxS", "yLxP", "yLxS"]
COMBO_LATEX = {
    "yHxP": r"$y_\text{H},\, x_\text{P}$",
    "yHxS": r"$y_\text{H},\, x_\text{S}$",
    "yLxP": r"$y_\text{L},\, x_\text{P}$",
    "yLxS": r"$y_\text{L},\, x_\text{S}$",
}

# Must match suggest_params() in Code/2.3.XGBoost.py
SEARCH_SPACE = [
    ("n_estimators", r"$n_\text{estimators}$", r"$[100,\,1500]$ (integer)"),
    ("max_depth", r"$d_\text{max}$", r"$[3,\,12]$ (integer)"),
    ("learning_rate", r"$\eta$", r"$[0.01,\,0.3]$ (log-uniform)"),
    ("subsample", r"subsample", r"$[0.5,\,1]$ (uniform)"),
    ("colsample_bytree", r"colsample_bytree", r"$[0.5,\,1]$ (uniform)"),
    ("min_child_weight", r"min_child_weight", r"$[0.5,\,10]$ (log-uniform)"),
    ("reg_lambda", r"$\lambda$", r"$[10^{-3},\,10]$ (log-uniform)"),
    ("reg_alpha", r"$\alpha$", r"$[10^{-3},\,10]$ (log-uniform)"),
]


def _fmt_val(name: str, val: float) -> str:
    if name in ("n_estimators", "max_depth"):
        return str(int(val))
    if name in ("learning_rate", "reg_lambda", "reg_alpha", "min_child_weight"):
        return f"{val:.4g}"
    return f"{val:.3f}"


def main() -> None:
    if not PARAMS_PATH.is_file():
        raise SystemExit(f"Missing {PARAMS_PATH}; run Code/2.3.XGBoost.py first.")

    df = pd.read_csv(PARAMS_PATH, sep="\t")
    by_combo = {str(r["combo"]): r for _, r in df.iterrows()}
    for co in COMBO_ORDER:
        if co not in by_combo:
            raise SystemExit(f"Missing combo {co} in {PARAMS_PATH}")

    n_trials = int(by_combo[COMBO_ORDER[0]]["n_trials"])
    n_cv = int(by_combo[COMBO_ORDER[0]]["n_cv"])

    lines: list[str] = [
        "% Generated by Code/3.1.xgb_hparams_table.py — do not edit by hand.",
        f"% Source: {PARAMS_PATH.name}; Optuna TPE, {n_trials} trials, {n_cv}-fold CV per combo.",
        r"\begin{table}[!ht]",
        r"\centering",
        r"\caption{XGBoost hyperparameter optimization with Optuna TPE. An independent study "
        rf"({n_trials} trials, {n_cv}-fold CV on the 2024 training year) is run for each "
        r"$(y,x)$ configuration. Search ranges are listed together with the selected values.}",
        r"\label{tb:xgb_hparams}",
        r"\small",
        r"\begin{tabular}{ll" + "c" * len(COMBO_ORDER) + "}",
        r"\toprule",
        r"Parameter & Search range & "
        + " & ".join(COMBO_LATEX[c] for c in COMBO_ORDER)
        + r" \\",
        r"\midrule",
    ]

    for key, lab, rng in SEARCH_SPACE:
        cells = [_fmt_val(key, float(by_combo[c][key])) for c in COMBO_ORDER]
        lines.append(f"{lab} & {rng} & " + " & ".join(cells) + r" \\")

    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\normalsize",
            r"\end{table}",
            "",
        ]
    )

    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    OUT_TEX.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote: {OUT_TEX}")


if __name__ == "__main__":
    main()
